### PR TITLE
upgrade a127-magic module

### PR DESCRIPTION
**Pull request by countcain**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 7265cd24047a4c3a0b7c0777ec054921c473664e
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/appirio-tech/lc1-discussion-service

---
This message was auto-generated by https://gitcop.com

**Comment by indytechcook** [comment]
You can ignore gitcop.  I need to turn him off ;)

**Comment by countcain** [comment]
Thanks.

**Comment by indytechcook** [comment]
Just a side thought.  What do you think about allowing overrides of the swagger config from the app config?

**Comment by countcain** [comment]
app config override swagger config? Why you need this?

**Pull request merged**
